---
ID: "66269b20-7ca6-480a-9590-31953013a1f5"
Parent: "1b145b73-45c9-4967-8345-378f2176dc6b"
Template: "1b145b73-45c9-4967-8345-378f2176dc6b"
Path: /sitecore/templates/Data Exchange/Providers/Brightcove/Folders/Brightcove Endpoints Root/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210909T202002Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
