---
ID: "45c681c8-860d-4019-803c-14a5a3c2a7ca"
Parent: "3a68c21b-5b14-48ba-875a-8da2c42afb91"
Template: "3a68c21b-5b14-48ba-875a-8da2c42afb91"
Path: /sitecore/templates/Data Exchange/Providers/Brightcove/Data Access/Value Accessors/CSV String Property Value Accessor/__Standard Values
DB: master
SharedFields:
- ID: "3c7f78cc-0c5c-4076-80ef-9a49fda5ff96"
  Hint: ConverterType
  Value: Brightcove.DataExchangeFramework.CsvStringPropertyValueAccessorConverter, Brightcove.DataExchangeFramework
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160310T175552Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
