---
ID: "dadd9166-2e13-4c0a-a381-5a1cfd4c5979"
Parent: "e168ec99-40fa-4f05-be21-42f22c399e4a"
Template: "e168ec99-40fa-4f05-be21-42f22c399e4a"
Path: /sitecore/templates/Data Exchange/Providers/Brightcove/Folders/Brightcove Value Accessor Sets Root/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210909T202003Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
