---
ID: "dff015b0-9d63-4ba3-af1a-2a14f8eaf4c1"
Parent: "de2ab6aa-2913-42b1-9d5f-f9ac74202190"
Template: "de2ab6aa-2913-42b1-9d5f-f9ac74202190"
Path: /sitecore/templates/Data Exchange/Providers/Brightcove/Folders/Brightcove Apply Mapping Rules Root/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210909T202002Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
