---
ID: "d72daa9c-bce1-4178-8020-8382f38b6078"
Parent: "db35d885-0519-4052-ae69-72d4116591ec"
Template: "186614bc-a123-4b7b-b2b6-2fa29c6894b0"
Path: /sitecore/media library/Media Framework/Accounts/Main Brightcove/Settings
DB: master
SharedFields:
- ID: "19b597d3-2edd-4ae2-aefe-4a94c7f10e31"
  Hint: __Source Item
  Value: "sitecore://master/{AAE37F9C-3A5D-4640-B718-19F396B1ADBA}"
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: 
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Settings
  Versions:
  - Version: 1
    Fields:
    - ID: "1b86697d-60ca-4d80-83fb-7555a2e6ce1c"
      Hint: __Source
      Value: "sitecore://master/{AAE37F9C-3A5D-4640-B718-19F396B1ADBA}?lang=en&ver=2"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171121T220050Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: 
