---
ID: "758cb8f2-3f33-3839-b425-63ad9e432c0d"
Parent: "01f80a34-c0e1-4d2e-9312-da26bd6ac84c"
Template: "de0f5bb5-1d51-41b2-ba4d-2c176c904bf3"
Path: /sitecore/media library/Media Framework/Accounts/Main Brightcove/Players/default
DB: master
SharedFields:
- ID: "6a3b39af-c59a-4e3f-86c8-eb0e846cf6e6"
  Hint: ID
  Value: default
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171121T233228Z
