---
ID: "c3018431-2f28-4272-af25-5c288cf8b7af"
Parent: "430b6498-8aaa-4880-a3a7-f30dcc8ee607"
Template: "430b6498-8aaa-4880-a3a7-f30dcc8ee607"
Path: /sitecore/templates/Data Exchange/Providers/Brightcove/Folders/Brightcove Value Readers Root/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210909T202003Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
